### ISSUE TITLE
Map on languages tab?

### ISSUE THREAD

**Issue by HedvigS** [clld/valpal#6]
Would it be swell with a map of the languages on [the languages tab :](https://valpal.info/contributions)D?

**Comment by xrotwang** [comment]
I think we're transitioning towards recommending
```shell
$ cldfbench cldfviz.map valpal/cldf/cldf-metadata.json --language-labels
```
instead.

**Comment by HedvigS** [comment]
Okay! If you're pushing to a non web-interface solution then I can just as well make maps on my own elsewhere, no problems. I was just thinking of people who mainly use the web interface
